import '../models/prevision.dart';

import '../models/region.dart';
import '../models/spot.dart';

const DUMMY_REGIONS = const [
  Region(
    "R1",
    "Normandie / Manche",
  ),
  Region(
    "R2",
    "Bretagne Nord",
  ),
  Region(
    "R3",
    "Bretagne Sud",
  ),
  Region(
    "R4",
    "Vendée",
  ),
  Region(
    "R5",
    "Charentes",
  ),
  Region(
    "R6",
    "Gironde",
  ),
  Region(
    "R7",
    "Landes",
  ),
  Region(
    "R8",
    "Pays Basque",
  ),
  Region(
    "R9",
    "Méditéranée Ouest",
  ),
  Region(
    "R10",
    "Méditéranée Est",
  ),
];

List<Spot> DUMMY_SPOT = [
  Spot(
    "S1",
    "Dunkerque",
    "https://www.surf-sentinel.com/sites/surf-sentinel.com/files/2018-08/spot-surf-dunkerque-bray-dunes.jpg",
    false,
    "R1",
  ),
  Spot(
    "S2",
    "Calais",
    "https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2016/08/13/node_33357/861902/public/2016/08/13/B979431943Z.1_20160813172148_000%2BGTG7D7MA9.1-0.jpg?itok=yBf8zBfh1471101726",
    false,
    "R1",
  ),
  Spot(
    "S3",
    "La Pointe Aux Oies",
    "https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2018/04/15/node_358950/39372743/public/2018/04/15/B9715399348Z.1_20180415161414_000%2BG5IB3BBVM.1-0.jpg?itok=ValbP-541523801665",
    false,
    "R1",
  ),
  Spot(
    "S4",
    "L'Anse Du Brick",
    "https://fr.wannasurf.com/spot/Europe/France/Normandy/Anse_du_Brick/photo/anse_du_brick03.jpg",
    false,
    "R1",
  ),
  Spot(
    "S5",
    "Les Petites Dalles",
    "https://web.kite-and-windsurfing-guide.com/images/spots/galleries/9306/_thumb1/Basse-Normandie-Les-Petites-Dalles-06-Nikedit.jpg",
    false,
    "R1",
  ),
  Spot(
    "S6",
    "Surtainville",
    "https://www.wikimanche.fr/images/thumb/c/c9/Surtainville-plage3.jpg/442px-Surtainville-plage3.jpg",
    false,
    "R1",
  ),
  Spot(
    "S7",
    "Le Rozel",
    "https://idata.over-blog.com/3/13/60/46/SURF/SURF00830.jpg",
    false,
    "R1",
  ),
  Spot(
    "S8",
    "Biville",
    "https://live.staticflickr.com/8050/8075203268_d83f217c5b_b.jpg",
    false,
    "R1",
  ),
  Spot(
    "S9",
    "Carolle",
    "https://www.surf-sentinel.com/sites/surf-sentinel.com/files/styles/spots_accueil/public/2018-05/spot-surf-pointe-chicard-yport-normandie.jpg?itok=2MdY8Rii",
    false,
    "R2",
  ),
  Spot(
    "S10",
    "Le Sillon",
    "https://sportyrent.com/wp-content/uploads/2014/01/spot-surf-35.jpg",
    false,
    "R2",
  ),
  Spot(
    "S11",
    "Cap Fréhel",
    "https://www.surf-sentinel.com/sites/surf-sentinel.com/files/2018-09/surf-report-cote-armor-greve-fosses-spot-surf.jpg",
    false,
    "R2",
  ),
  Spot(
    "S12",
    "Perros-Guirec",
    "https://www.surf-report.com/img/pictures/2015/20150404/1504041035.jpg",
    false,
    "R2",
  ),
  Spot(
    "S13",
    "Pors Ars Villec",
    "https://surfplaya.com/wp-content/uploads/2016/12/porza1.jpg",
    false,
    "R2",
  ),
  Spot(
    "S14",
    "Les Sables Blancs",
    "https://api.tourism-system.com/resize/crop/1200/627/60/aHR0cHM6Ly9icmV0YWduZS5tZWRpYS50b3VyaW5zb2Z0LmV1L3VwbG9hZC9MZXMtc2FibGVzLWJsYW5jcy00LmpwZw==/image.jpg",
    false,
    "R2",
  ),
  Spot(
    "S15",
    "Moulin De La Rive",
    "https://www.toutcommenceenfinistere.com/sites/default/files/2019-02/baie-trepasses.jpg",
    false,
    "R2",
  ),
  Spot(
    "S16",
    "Le Petit Minou",
    "https://www.surf-sentinel.com/sites/surf-sentinel.com/files/2018-07/spot-surf-petit-minou-brest.jpg",
    false,
    "R2",
  ),
  Spot(
    "S17",
    "Saint Tugen",
    "https://www.surf-forecast.com/system/images/16921/small_illustration/Saint-Tugen.jpg",
    false,
    "R3",
  ),
  Spot(
    "S18",
    "La Gamelle",
    "https://imgv3.surf-report.com/pictures/2018/20180327/thumbnail/mobile/1803275127.png",
    false,
    "R3",
  ),
  Spot(
    "S19",
    "La Torche",
    "https://media.routard.com/image/47/9/pt114876.1323479.w430.jpg",
    false,
    "R3",
  ),
  Spot(
    "S20",
    "Port Blanc",
    "https://images.location-et-vacances.com/images_1024/photo_2168467.jpg",
    false,
    "R3",
  ),
  Spot(
    "S21",
    "Saint-Jean-De-Mont",
    "https://www.surf-report.com/img/pictures/reports/2019/20190518/19051884686.jpg",
    false,
    "R4",
  ),
  Spot(
    "S22",
    "Saint Gilles-Croix-De-Vie",
    "https://imgv3.surf-report.com/pictures/2018/20180327/thumbnail/mobile/1803275127.png",
    false,
    "R4",
  ),
  Spot(
    "S23",
    "SauveTerre",
    "https://www.surf-forecast.com/system/images/22012/large/sa-DSCF5086-plage-sauveterre.jpg?1581514061",
    false,
    "R4",
  ),
  Spot(
    "S24",
    "La Mine",
    "https://img.surfsession.com/pictures/2019/20190425/thumbnail/1904259223.png",
    false,
    "R4",
  ),
  Spot(
    "S25",
    "Les Grenettes",
    "https://www.realahune.fr/wp-content/uploads/2013/05/spot-620x300.jpg",
    false,
    "R5",
  ),
  Spot(
    "S26",
    "Rivedoux",
    "https://i.ytimg.com/vi/hhpN1hf6_IU/maxresdefault.jpg",
    false,
    "R5",
  ),
  Spot(
    "S27",
    "Aytré",
    "https://www.surfsession.com/img/pictures/2015/20150319/1503192576.jpg",
    false,
    "R5",
  ),
  Spot(
    "S28",
    "Chassiron",
    "https://www.surfsession.com/img/pictures/2015/20150623/1506238015.jpg",
    false,
    "R5",
  ),
  Spot(
    "S29",
    "Le Verdon",
    "https://www.surf-forecast.com/system/images/1433/large/Guidel-Plages.jpg?1284125858",
    false,
    "R6",
  ),
  Spot(
    "S30",
    "Soulac",
    "https://www.surf-forecast.com/system/images/15367/large/Soulacsur-Mer.jpg?1452031068",
    false,
    "R6",
  ),
  Spot(
    "S31",
    "Le pin sec",
    "https://media-cdn.tripadvisor.com/media/photo-m/1280/18/04/42/5f/plage-du-pin-sec.jpg",
    false,
    "R6",
  ),
  Spot(
    "S32",
    "Lacanau",
    "https://sportyrent.com/wp-content/uploads/2011/11/spot-1-75.jpg",
    false,
    "R6",
  ),
  Spot(
    "S33",
    "Les Estagnots",
    "https://ec2-im-1.msw.ms/md/image.php?id=393392&type=PHOTOLAB&resize_type=STREAM_MEDIUM_SQUARE&fromS3",
    false,
    "R7",
  ),
  Spot(
    "S34",
    "Le Santocha",
    "https://www.landesatlantiquesud.com/wp-content/uploads/wpetourisme/PLAGE-SANTOCHA--SAVANE.JPG",
    false,
    "R7",
  ),
  Spot(
    "S35",
    "La Gravière",
    "https://www.surf-forecast.com/system/images/15868/large/La-Graviere.jpg?1457988917",
    false,
    "R7",
  ),
  Spot(
    "S36",
    "Les Bourdaines",
    "https://webcam-hd.fr/media/apps/seignossebourdainesbig.jpg",
    false,
    "R7",
  ),
  Spot(
    "S37",
    "Sainte Barbe",
    "https://cdt64.media.tourinsoft.eu/upload/Plage-2-3.jpg?width=1000&height=625&crop=1",
    false,
    "R8",
  ),
  Spot(
    "S38",
    "Hendaye",
    "https://www.lehena.com/wp-content/uploads/2014/06/hendaye-pays-basque-lehena.jpg",
    false,
    "R8",
  ),
  Spot(
    "S39",
    "Uhabia",
    "https://api.tourism-system.com/resize/clip/782/400/80/aHR0cDovL2NkdDQwLm1lZGlhLnRvdXJpbnNvZnQuZXUvdXBsb2FkL3VoYWJpYS1iaWRhcnQtcGF5cy1iYXNxdWUtLTItLkpQRw==/image.jpg",
    false,
    "R8",
  ),
  Spot(
    "S40",
    "Bidart Centre",
    "https://cdt64.media.tourinsoft.eu/upload/CentreB.JPG?width=1000&height=625&crop=1",
    false,
    "R8",
  ),
  Spot(
    "S41",
    "La Grande Plage",
    "https://cdn.generationvoyage.fr/2019/01/surf-plage-biarritz.jpg",
    false,
    "R8",
  ),
  Spot(
    "S42",
    "Cenitz",
    "https://media-cdn.tripadvisor.com/media/photo-s/08/8d/05/72/plage-de-cenitz.jpg",
    false,
    "R8",
  ),
  Spot(
    "S43",
    "Parlementia",
    "https://www.ecole-de-surf-guethary-bidart.com/images/diapo/ecole-surf-guethary-Wfa1Q.jpg",
    false,
    "R8",
  ),
  Spot(
    "S44",
    "Palavas les Flots",
    "https://r-cf.bstatic.com/images/hotel/max1024x768/165/165105375.jpg",
    false,
    "R9",
  ),
  Spot(
    "S45",
    "Sainte Marie De La Mer",
    "https://aubergecavaliere.com/wp-content/uploads/2019/08/Plages-Saintes-Maries.jpg",
    false,
    "R9",
  ),
  Spot(
    "S46",
    "Sausset Les Pins",
    "https://upload.wikimedia.org/wikipedia/commons/f/f1/La_corniche_de_Sausset-les-Pins_en_2018..jpg",
    false,
    "R9",
  ),
  Spot(
    "S47",
    "Carro",
    "https://p6.storage.canalblog.com/69/93/1192058/93698250_o.jpg",
    false,
    "R9",
  ),
  Spot(
    "S48",
    "Saint-Cyprien",
    "https://www.tourisme-saint-cyprien.com/sites/default/files/styles/full_screen/public/sit/images/LOILAR066V50QY4C/plage-de-la-lagune-saint-cyprien-1920px.jpg?h=197483aa&itok=ELlPSWQq",
    false,
    "R9",
  ),
  Spot(
    "S49",
    "Sète",
    "https://i.ytimg.com/vi/EswTPil6soM/maxresdefault.jpg",
    false,
    "R9",
  ),
  Spot(
    "S50",
    "La Courone",
    "https://www.la13emevague.com/wp-content/uploads/2016/03/plage-de-sainte-croix.jpg",
    false,
    "R9",
  ),
  Spot(
    "S51",
    "Cassis",
    "https://www.plages.tv/gallery/cms/images/plage-arene-cassis-13.jpg",
    false,
    "R9",
  ),
  Spot(
    "S52",
    "Cap Saint-Louis",
    "https://fr.wannasurf.com/spot/Europe/France/Mediterranean/cap_saint_louis/photo/capstlouis1.jpg",
    false,
    "R9",
  ),
  Spot(
    "S53",
    "Les Sablettes",
    "https://www.surf-forecast.com/system/images/11375/large/Les-Sablettes.jpg?1407736450",
    false,
    "R9",
  ),
  Spot(
    "S54",
    "Vintimille",
    "https://i.ytimg.com/vi/09Cb-EtfGyM/maxresdefault.jpg",
    false,
    "R10",
  ),
  Spot(
    "S55",
    "Baie Du Soleil",
    "https://pennarbled.files.wordpress.com/2015/05/dsc00076.jpg",
    false,
    "R10",
  ),
  Spot(
    "S56",
    "Villefranche Sur Mer",
    "https://i.ytimg.com/vi/P_QDzyAU3CQ/maxresdefault.jpg",
    false,
    "R10",
  ),
  Spot(
    "S57",
    "Le Lavandou",
    "https://www.surf-forecast.com/system/images/9145/large/Le-Lavandou.jpg?1382763419",
    false,
    "R10",
  ),
];

final DUMMY_PREVISION = [
  Prevision(
    "P1",
    new DateTime.now(),
    10,
    21,
    10,
    "17:05",
    "06:00",
    "11:30",
    "22:00",
    "S39",
  ),
];
